# Generated by Django 2.0.5 on 2018-10-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_date', models.DateField(blank=True, null=True)),
                ('e_start', models.TimeField(blank=True, null=True)),
                ('e_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=255)),
                ('m_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('u_username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('u_password', models.CharField(max_length=255)),
                ('u_varsity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='varsity',
            fields=[
                ('v_num', models.IntegerField(primary_key=True, serialize=False)),
                ('v_email', models.CharField(max_length=255)),
                ('v_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='m_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='websites.varsity'),
        ),
        migrations.AddField(
            model_name='event',
            name='e_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='websites.varsity'),
        ),
    ]
