# Generated by Django 2.0.5 on 2018-10-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsity',
            name='v_contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='varsity',
            name='v_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
