# Generated by Django 2.0.5 on 2018-10-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20181028_2310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='eventlol',
        ),
    ]
