# Generated by Django 2.0.5 on 2018-10-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20181029_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlol',
            name='e_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventlol',
            name='e_end',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventlol',
            name='e_start',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
